Tests for union based sql injection
SasanLabs/VulnerableApp pull request #444
Opened 2023-09-12 15:15 UTC by 000panther

As requested in #393 i added some tests for the base cases.

2023-09-12 18:45 UTC, preetkaran20 commented on src/main/java/org/sasanlabs/service/vulnerability/sqlInjection/UnionBasedSQLInjectionVulnerability.java
> +                this::resultSetToResponse);
Amazing!!! Thanks for the change.

2023-09-12 18:45 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/sqlInjection/UnionBasedSQLInjectionVulnerabilityTest.java
> +import static org.mockito.ArgumentMatchers.*;
please use specific imports instead of *

2023-09-12 18:46 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/sqlInjection/UnionBasedSQLInjectionVulnerabilityTest.java
> +        unionBasedSQLInjectionVulnerability = Mockito.spy(new UnionBasedSQLInjectionVulnerability(template));
do we need spy here?

2023-09-12 18:47 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/sqlInjection/UnionBasedSQLInjectionVulnerabilityTest.java
> +        template = Mockito.spy(new JdbcTemplate());
shall we use @Mock instead of spy?

2023-09-12 18:47 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/sqlInjection/UnionBasedSQLInjectionVulnerabilityTest.java
> +        params.put("id", "1 UNION SELECT * FROM cars;");
shall we use singletonMap here?

2023-09-12 18:49 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/sqlInjection/UnionBasedSQLInjectionVulnerabilityTest.java
> +        doReturn(null)
I think you can directly define the mock on same template method. can you please check it once.

2023-09-12 18:49 UTC, preetkaran20 commented
@000panther please use SpotlessApply so that alignment issues gets resolved.

2023-09-12 18:50 UTC, preetkaran20 requested changes
Please fix the spotless apply.

2023-09-15 08:41 UTC, 000panther commented on src/test/java/org/sasanlabs/service/vulnerability/sqlInjection/UnionBasedSQLInjectionVulnerabilityTest.java
> +        params.put("id", "1 UNION SELECT * FROM cars;");
Nice Idea!

2023-09-15 18:24 UTC, preetkaran20 approved these changes
Thanks a lot @000panther. 🚀

2023-09-15 18:25 UTC, merged