Pushing test for Persistent XSS in HTML
SasanLabs/VulnerableApp pull request #455
Opened 2023-11-18 14:46 UTC by SeheX

2023-11-18 21:44 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/xss/reflected/PersistentXSSInHTMLTagVulnerabilityTest.java
> +        Map<String, String> queryParams = new HashMap<>();
i think we can use collections.singletonMap

2023-11-21 19:34 UTC, preetkaran20 requested changes

2023-11-21 19:34 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/xss/reflected/PersistentXSSInHTMLTagVulnerabilityTest.java
> +        verify(postRepository, times(1)).save(any());
shall we also assert on the arguments passed to the postRepository?

2023-11-21 19:34 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/xss/reflected/PersistentXSSInHTMLTagVulnerabilityTest.java
> +    public void testGetVulnerablePayloadLevel6() {
I think adding a few tests would help here like input having NullByte and its impact on level 6 and level 5.

2023-11-21 19:34 UTC, preetkaran20 commented on src/test/java/org/sasanlabs/service/vulnerability/xss/reflected/PersistentXSSInHTMLTagVulnerabilityTest.java
> +        verify(postRepository, times(1)).save(any());
I think we need to add a few more granular level of assertions then just verifying the call to postRepository.

2023-11-27 23:19 UTC, SeheX commented
Can you check ? Is it good like this ?

2023-11-29 06:53 UTC, preetkaran20 approved these changes
LGTM. Thanks a lot for the PR.

2023-11-29 07:02 UTC, preetkaran20 commented
@SeheX Thanks a lot for the PR !!!

2023-11-29 07:03 UTC, merged